name: Yolo5 Microservice Deployment Main

on:
  workflow_dispatch:
    inputs:
      us-east-1:
        description: 'N.Virginia (us-east-1)'
        required: false
        type: boolean
      eu-north-1:
        description: 'Stockholm (eu-north-1)'
        required: false
        type: boolean

jobs:
  us-east-1:
    if: ${{ github.event.inputs.us-east-1 == 'true' }}
    uses: ./.github/workflows/polybot-deployment-region.yaml
    with:
      region-code: us-east-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PRIVATE_KEY: ${{ secrets.US_EAST_1_PRIVATE_KEY }}

  eu-north-1:
    if: ${{ github.event.inputs.eu-north-1 == 'true' }}
    uses: ./.github/workflows/polybot-deployment-region.yaml
    with:
      region-code: eu-north-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PRIVATE_KEY: ${{ secrets.EU_NORTH_1_PRIVATE_KEY }}